[build]
  base = "/"  # Root directory
  command = "pnpm build"  # Build the functions
  publish = "static"  # Publish static files from the "static" directory

[context.production.environment]
  NODE_ENV = "production"
