[build]
  command = "go build"  # Specify your build command
  publish = "public"    # Set the correct directory for your build output

[build.environment]
  GO_VERSION = "1.19"  # Specify Go version 1.19 to install it during the build process

[[plugins]]
  package = "@netlify/plugin-go"  # Add a plugin to install Go version 1.19 if needed
