[build]
  command = "go build"  # Or your build command if it's different
  publish = "public"    # Or the correct directory where your build output is

[build.environment]
  GO_VERSION = "1.19"  # Specify the Go version
