[build]
  command = "pnpm run build"  # If you have a build command, change accordingly
  publish = "dist"            # Adjust if your publish directory is different

[[plugins]]
package = "@netlify/plugin-pnpm"  # Ensure the pnpm plugin is included
