[build]
  command = "pnpm install && pnpm run build"
  publish = "."

[context.production.environment]
  NODE_VERSION = "18.12"  # Set Node.js version to v18.12
  PNPM_VERSION = "7"  # Use the pnpm version you want

[[plugins]]
  package = "@netlify/plugin-pnpm"
