[build]
  command = "pnpm install && pnpm run build"
  publish = "."

[context.production.environment]
  NODE_VERSION = "16"  # Set to the Node version you need
  PNPM_VERSION = "7"  # Use the pnpm version you want

[[plugins]]
  package = "@netlify/plugin-pnpm"
