[build]
  command = "pnpm run build"  # Your build command, make sure it's correctly set
  publish = "public"          # Replace with your actual publish directory

[[plugins]]
  package = "@netlify/plugin-pnpm"  # Added the plugin to the build configuration

[build.environment]
  NETLIFY_USE_PNPM = "true"  # Ensure that PNPM is used during the build process
  GO_VERSION = "1.19"        # Specify Go version if needed (optional)
